name: delete
on:
  workflow_dispatch:
    inputs:
      minimumRunsToKeep:
        description: 'Number of workflow runs to keep'
        required: true
        default: 12
      workflowName:
        description: 'Name of workflow to delete from'
        required: true
        default: 'status'
  schedule:
    - cron: "1 */2 * * *"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: ${{ github.event.inputs.workflowName }}