name: status

on:
#  push:
#    branches: 
#      - main
#  pull_request:
#    branches:
#      - main
  schedule:
    - cron: "0 * * * *"

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          UPDATE_OPTION: MARKDOWN
          MARKDOWN_FILE: README.md
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7dd9705e7927883a634d337e39b59d28
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
    steps: 
    - name: Run hello world
      run: |-
        echo "hello world"